# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="dnimagitech"
version="${file.jarVersion}"
displayName="DNI Magitech"
# credits="The DNI Magi dev team"
authors="DaiNekoIchi, PADS"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.dnimagitech]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dnimagitech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
